name: backend-ci-cd

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    if: github.repository == 'sonyeongeun/capstoneDesign_HEJZ'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: yeongeunsong/ustar-back
      TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle build
        working-directory: HEJZ_back
        run: ./gradlew clean build -x test

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        run: |
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest HEJZ_back
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /srv/ustar
            export TAG=${{ env.TAG }}
            docker compose pull
            docker compose up -d
            docker image prune -f
